export enum GetDataPaths {
	TAG_LINE = '/tagline',
	LOGO = '/logo',
	ADDRESS = '/address',
	WORKING_TIME = '/working-time',
	PHONE_NUMBER = '/phone-number',
	DOCTORS = '/doctors',
	DEVICES = '/devices',
	NEWS = '/news',
	ABOUT = '/about',
	DOCUMENTS = '/documents',
	SERVICES_TYPES = '/services-types',
	CAROUSEL_IMAGES = '/carousel-images',
	SLIDER_IMAGES = '/sliders',
	HEAD_EXCELLENCE = '/head-excellence',
	EXCELLENCES = '/excellences',
	REVIEWS = '/reviews',
	POLICY_PRIVACY = '/policy-privacy',
	RESUME = '/vakancyes',
	LICENSES = '/licenses',
	ARTICLES = '/articles',
	SOCIAL_LINKS = '/social-link',
	CALLBACKS = '/callbacks'
}